single_plot_params = dict( fig_width_abs       = 3.5,
                           left_margin_abs     = 0.45,
                           right_margin_abs    = 0.05,
                           top_margin_abs      = 0.05,
                           bottom_margin_abs   = 0.35,
                           xlabel_bottom_y_abs = 0.01,
                           aspect_ratio        = 1.618,
                           label_fontsize      = 11,
                           ticklabel_fontsize  = 8   )
## single_plot_params = dict( figsize_inch       = [3.5,2.254],
##                            axes_boxes         = [[0.129,.155,.857,.823]],
##                            ylabel_left_x      = 0.01,
##                            xlabel_bottom_y    = 0.01,
##                            label_fontsize     = 11,
##                            ticklabel_fontsize = 8   )

mpp_params = dict( fig_width_abs       = 7,
                   aspect_ratio        = 1.618,
                   dx_pad_abs          = 0.1,
                   dy_pad_abs          = 0.1,
                   left_margin_abs     = 0.45,
                   right_margin_abs    = 0.05,
                   top_margin_abs      = 0.2,
                   bottom_margin_abs   = 0.35,
                   xlabel_bottom_y_abs = 0.01,
                   xlabel_top_y_abs    = 0.01,
                   ylabel_left_x_abs   = 0.01,
                   ylabel_right_x_abs  = 0.10 )
